# version: '3.8'
# version attribute removed as it is obsolete
services:
  kolam-ai-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount model files and generated content
      - ./backend/models:/app/backend/models:ro
      - ./backend/generated_images:/app/backend/generated_images
      - ./backend/dataset_analysis:/app/backend/dataset_analysis
      - ./backend/temp:/app/backend/temp
    environment:
      - PYTHONPATH=/app
      - MODEL_PATH=/app/backend/models
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  # Optional: Nginx for reverse proxy and static files
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./backend/generated_images:/usr/share/nginx/html/generated:ro
  #   depends_on:
  #     - kolam-ai-api
  #   restart: unless-stopped

# volumes:
#   redis_data:
